server:
  port: 8080

spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.19.190.170:3366/myifo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    password: 123456

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.chujie.framework.demo1.entity

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
